name: External Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build
        with:
          # dependencies-bot-name:
          # is-publish:
          build-os: ${{ matrix.os }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          # artifacts-paths: |
          #   dist/file-*-1.txt
          #   dist/file-*-2.txt
          artifacts-paths: |
            dist/latest*.yml
            dist/*.exe
            dist/*.AppImage
            dist/*.dmg
            dist/*.rpm
            dist/*.deb
            dist/*.zip
            dist/*.blockmap
