name: BuildTest

# on: [push, pull_request, workflow_call]
# on: [workflow_call]
on: [push]

permissions:
  # Required for Electron Builder to create and update releases on Github
  contents: write

env:
  DEPENDENCIES_BOT_NAME: "dependabot[bot]"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os}}

    steps:
      - name: Create a File
        run: |
          mkdir dist
          echo "hello from ${{ matrix.os }}" > dist/file-${{ matrix.os }}-1.txt
          echo "hello again from ${{ matrix.os }}" > dist/file-${{ matrix.os }}-2.txt
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*.txt
          retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          # run-id: ${{ github.event.workflow_run.id }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: build-*/*-1.txt
          path: my-artifact
          merge-multiple: true
      - run: ls -R
