name: Release

# on: [push, pull_request]

# on:
#   workflow_call:
#   workflow_run:
#   #   workflows: [Build Test]
#   #   types: [completed]
on:
  pull_request:
    branches: [homebrew-test]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'chore/release')
    # uses: ${{github.repository}}/.github/workflows/build-int.yml@${{github.ref}}
    uses: ./.github/workflows/build-int.yml
    with:
      artifacts-paths: |
        dist/file-*-1.txt
        dist/file-*-2.txt
    # with:
    #   artifacts-paths: |
    #     dist/latest*.yml
    #     dist/*.exe
    #     dist/*.AppImage
    #     dist/*.dmg
    #     dist/*.rpm
    #     dist/*.deb
    #     dist/*.zip
    #     dist/*.blockmap

  release:
    needs: [build]
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true && contains(github.head_ref, 'chore/release')
    # if: github.event.pull_request.merged == true && contains(github.head_ref, 'chore/release')

    steps:
      # - name: Build
      #   uses: ${{ github.repository }}/.github/workflows/build.yml@${{ github.ref }}
      - run: echo ${{github.head_ref}}
      - run: echo ${{github.base_ref}}
      - run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
      # - name: Build Test
      #   uses: ${{ github.repository }}/.github/workflows/build-test.yml@${{ github.ref#refs/heads/ }}
      # - name: Download artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     # run-id: ${{ github.event.workflow_run.id }}
      #     # github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pattern: build-*
      #     # path: my-artifact
      #     merge-multiple: true
      # - run: ls -R
